server:
  port: 8088

#logging:
#  level:
#    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hiberante:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: username
      password: passWord